name: GitHub Pull Request Action
author: Wei He <github@weispot.com>
description: ⤵️ Create pull request
branding:
  icon: 'git-pull-request'
  color: 'black'
inputs:
  source_branch:
    description: Branch name to pull from, default is triggered branch
    required: false
  destination_branch:
    description: Branch name to sync to in this repo, default is master
    required: false
    default: master
  repository:
    required: false
    description: Repository on which to perform the pull-request. Defaults to current repo. Can different from the current one.
  pr_title:
    description: Pull request title
    required: false
  pr_body:
    description: Pull request body
    required: false
  pr_template:
    description: Pull request template
    required: false
  pr_reviewer:
    description: Pull request reviewers, comma-separated list (no spaces)
    required: false
  pr_assignee:
    description: Pull request assignees, comma-separated list (no spaces)
    required: false
  pr_label:
    description: Pull request labels, comma-separated list (no spaces)
    required: false
  pr_milestone:
    description: Pull request milestone
    required: false
  pr_draft:
    description: Draft pull request
    required: false
  pr_allow_empty:
    description: Create PR even if no changes
    required: false
  token:
    description: GitHub token secret or Personal Access Token
    required: true
  debug:
    description: Bash set -x debugging mode
outputs:
  pr_url:
    description: 'Pull request URL'
  pr_number:
    description: 'Pull request number'
  has_changed_files:
    description: 'Boolean string indicating whether any file has been changed'
runs:
  using: 'docker'
  image: 'Dockerfile'
